### ISSUE TITLE
Neg-NSD training?

### ISSUE THREAD

**Issue by ZHUXUHAN** [muktilin/NICE#3]
## ❓ Questions and Help
hi, how can i just train the model with NSD datasets, just which file i can use in new data files, or how can i reproduce the reported table 3-(a) ?

**Comment by muktilin** [comment]
You can follow the nice training command and comment out the following code so that it doesn't change positive noisy labels.

if all_id in filter_noisy_subset.item().keys():
      self.relationships[int(all_id)][filter_noisy_id, 2] = np.array(change_label)

**Comment by ZHUXUHAN** [comment]
I think this setting is not in accordance with the principle of the Neg-NSD method, the method does not remove the noisy positive labels, that is, change them to negative labels, but I print these new labels, found that it removes some of the positive labels that seem to be noisy.

**Comment by muktilin** [comment]
> I think this setting is not in accordance with the principle of the Neg-NSD method, the method does not remove the noisy positive labels, that is, change them to negative labels, but I print these new labels, found that it removes some of the positive labels that seem to be noisy.
In Neg-NSD setting, we just detect missing labeled triplets (negative noisy labels), and complete the labels of these triplets, there is no operation to change the label in original dataset. In generate_has_rels_results.py, we extract all annotated labels in original dataset and in generate_nsd_results.py, we append the newly annotated labels with original annotated labels. I may not understand your question very well. For more details, you can contact me through email and chat with me on wechat.
