### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by bowen-upenn** [muktilin/NICE#6]
## ❓ Questions and Help

We are researchers also working on the topics of scene graphs, and we find your work to be quite related and inspiring to us. We wonder if you would be willing to share your cleaner version of the Visual Genome dataset, i.e., `\tilde{\mathcal{T}}_{\text {clean }}^{+} \cup \tilde{\mathcal{T}}_{\text {noisy } \rightarrow \text { clean }}^{+} \cup \mathcal{T}_{\text {clean }}^{-}`, mentioned at the end of the second paragraph of Section 3 in your paper. Your help will speed up our progress, and we sincerely appreciate it. We can also be reached at bwjiang@seas.upenn.edu, if you prefer. Thanks again.

**Comment by muktilin** [comment]
You only need to refer to the operation type=nice in visual_genome.py and download the relevant files(https://drive.google.com/drive/folders/1JDNeUdug2ewLlRID3yepKVgjw5PenE50) to train with the clean dataset.
